const countries = [
  { rus: "Австрийская Республика", eng: "Republic of Austria" },
  { rus: "Азербайджанская Республика", eng: "Republic of Azerbaijan" },
  { rus: "Аландские острова", eng: "Åland Islands" },
  { rus: "Американское Самоа", eng: "American Samoa" },
  { rus: "Ангилья", eng: "Anguilla" },
  { rus: "Антарктида", eng: "Antarctica" },
  { rus: "Антигуа и Барбуда", eng: "Antigua and Barbuda" },
  { rus: "Арабская Республика Египет", eng: "Arab Republic of Egypt" },
  { rus: "Аргентинская Республика", eng: "Argentine Republic" },
  { rus: "Аруба", eng: "Aruba" },
  { rus: "Барбадос", eng: "Barbados" },
  { rus: "Белиз", eng: "Belize" },
  { rus: "Бермудские острова", eng: "Bermuda" },
  {
    rus: "Боливарианская Республика Венесуэла",
    eng: "Bolivarian Republic of Venezuela",
  },
  {
    rus: "Большинство Serene Республика Сан-Марино",
    eng: "Republic of San Marino",
  },
  {
    rus: "Бонэйр, Синт-Эстатиус и Саба",
    eng: "Bonaire, Sint Eustatius and Saba",
  },
  { rus: "Босния и Герцеговина", eng: "Bosnia and Herzegovina" },
  {
    rus: "Британская территория Индийского океана",
    eng: "British Indian Ocean Territory",
  },
  { rus: "Буркина -Фасо", eng: "Burkina Faso" },
  {
    rus: "Великое Герцогство Люксембург",
    eng: "Grand Duchy of Luxembourg",
  },
  { rus: "Венгрия", eng: "Hungary" },
  { rus: "Виргинские острова", eng: "Virgin Islands" },
  {
    rus: "Виргинские острова Соединенных Штатов",
    eng: "Virgin Islands of the United States",
  },
  {
    rus: "Внешние малые острова США",
    eng: "United States Minor Outlying Islands",
  },
  {
    rus: "Восточной Республики Уругвай",
    eng: "Oriental Republic of Uruguay",
  },
  { rus: "Габона Республика", eng: "Gabonese Republic" },
  { rus: "Гваделупа", eng: "Guadeloupe" },
  { rus: "Гвиана", eng: "Guiana" },
  { rus: "Гибралтар", eng: "Gibraltar" },
  {
    rus: "Гонконг",
    eng: "Hong Kong",
  },
  { rus: "Город-государство Ватикан", eng: "Vatican City State" },
  { rus: "Государство Израиль", eng: "State of Israel" },
  { rus: "Государство Катар", eng: "State of Qatar" },
  { rus: "Государство Кувейт", eng: "State of Kuwait" },
  { rus: "Государство Ливии", eng: "State of Libya" },
  { rus: "Государство Палестина", eng: "State of Palestine" },
  { rus: "Государство Эритрея", eng: "State of Eritrea" },
  { rus: "Гренада", eng: "Grenada" },
  { rus: "Гренландия", eng: "Greenland" },
  { rus: "Греческая Республика", eng: "Hellenic Republic" },
  { rus: "Грузия", eng: "Georgia" },
  { rus: "Гуам", eng: "Guam" },
  {
    rus: "Демократическая Республика Конго",
    eng: "Democratic Republic of the Congo",
  },
  {
    rus: "Демократическая Республика Сан-Томе и Принсипи",
    eng: "Democratic Republic of São Tomé and Príncipe",
  },
  {
    rus: "Демократическая Республика Тимор -Лешти",
    eng: "Democratic Republic of Timor-Leste",
  },
  {
    rus: "Демократическая Социалистическая Республика Шри-Ланка",
    eng: "Democratic Socialist Republic of Sri Lanka",
  },
  { rus: "Департамент Майотта", eng: "Department of Mayotte" },
  { rus: "Доминиканская Республика", eng: "Dominican Republic" },
  {
    rus: "Иорданского Хашимитского Королевства",
    eng: "Hashemite Kingdom of Jordan",
  },
  { rus: "Ирландия", eng: "Republic of Ireland" },
  {
    rus: "Исламская Республика Афганистан",
    eng: "Islamic Republic of Afghanistan",
  },
  { rus: "Исламская Республика Иран", eng: "Islamic Republic of Iran" },
  {
    rus: "Исламская Республика Мавритания",
    eng: "Islamic Republic of Mauritania",
  },
  {
    rus: "Исламская Республика Пакистан",
    eng: "Islamic Republic of Pakistan",
  },
  { rus: "Исландия", eng: "Iceland" },
  { rus: "Итальянская Республика", eng: "Italian Republic" },
  { rus: "Йеменская Республика", eng: "Republic of Yemen" },
  { rus: "Каймановы острова", eng: "Cayman Islands" },
  { rus: "Канада", eng: "Canada" },
  { rus: "Китайская Республика", eng: "Republic of China (Taiwan)" },
  { rus: "Княжество Андорра", eng: "Principality of Andorra" },
  { rus: "Княжество Лихтенштейн", eng: "Principality of Liechtenstein" },
  { rus: "Княжество Монако", eng: "Principality of Monaco" },
  {
    rus: "Коллективность Санкт -Бартельми",
    eng: "Collectivity of Saint Barthélemy",
  },
  {
    rus: "Кооперативная Республика Гайана",
    eng: "Co-operative Republic of Guyana",
  },
  {
    rus: "Корейская Народно-Демократическая Республика Корея",
    eng: "Democratic People's Republic of Korea",
  },
  { rus: "Королевство Бахрейн", eng: "Kingdom of Bahrain" },
  { rus: "Королевство Бельгия", eng: "Kingdom of Belgium" },
  { rus: "Королевство Бутан", eng: "Kingdom of Bhutan" },
  { rus: "Королевство Дания", eng: "Kingdom of Denmark" },
  { rus: "Королевство Испания", eng: "Kingdom of Spain" },
  { rus: "Королевство Камбоджа", eng: "Kingdom of Cambodia" },
  { rus: "Королевство Лесото", eng: "Kingdom of Lesotho" },
  { rus: "Королевство Марокко", eng: "Kingdom of Morocco" },
  { rus: "Королевство Норвегия", eng: "Kingdom of Norway" },
  { rus: "Королевство Саудовская Аравия", eng: "Kingdom of Saudi Arabia" },
  { rus: "Королевство Свазиленд", eng: "Kingdom of Eswatini" },
  { rus: "Королевство Таиланд", eng: "Kingdom of Thailand" },
  { rus: "Королевство Тонга", eng: "Kingdom of Tonga" },
  { rus: "Королевство Швеция", eng: "Kingdom of Sweden" },
  { rus: "Коронное владение Гернси", eng: "Bailiwick of Guernsey" },
  { rus: "Коронное владение Джерси", eng: "Bailiwick of Jersey" },
  { rus: "Кыргызская Республика", eng: "Kyrgyz Republic" },
  {
    rus: "Лаосская Народно-Демократическая Республика",
    eng: "Lao People's Democratic Republic",
  },
  { rus: "Латвийская Республика", eng: "Republic of Latvia" },
  { rus: "Ливанская Республика", eng: "Lebanese Republic" },
  { rus: "Литовская Республика", eng: "Republic of Lithuania" },
  { rus: "Малайзия", eng: "Malaysia" },
  { rus: "Мартиника", eng: "Martinique" },
  { rus: "Мексиканские Соединённые Штаты", eng: "United Mexican States" },
  {
    rus: "Многонациональное Государство Боливия",
    eng: "Plurinational State of Bolivia",
  },
  { rus: "Молдова", eng: "Republic of Moldova" },
  { rus: "Монголия", eng: "Mongolia" },
  { rus: "Монтсеррат", eng: "Montserrat" },
  {
    rus: "Народная Республика Бангладеш",
    eng: "People's Republic of Bangladesh",
  },
  { rus: "Народная Республика Китай", eng: "People's Republic of China" },
  {
    rus: "Народно-Демократическая Республика Алжир",
    eng: "People's Democratic Republic of Algeria",
  },
  {
    rus: "Нация Бруней, обитель мира",
    eng: "Nation of Brunei, Abode of Peace",
  },
  {
    rus: "Независимое Государство Папуа-Новой Гвинеи",
    eng: "Independent State of Papua New Guinea",
  },
  {
    rus: "Независимое Государство Самоа",
    eng: "Independent State of Samoa",
  },
  {
    rus: "Независимой и суверенной Республики Кирибати",
    eng: "Independent and Sovereign Republic of Kiribati",
  },
  { rus: "Нидерланды", eng: "Kingdom of the Netherlands" },
  { rus: "Ниуэ", eng: "Niue" },
  { rus: "Новая Зеландия", eng: "New Zealand" },
  { rus: "Новая Каледония", eng: "New Caledonia" },
  {
    rus: "Объединенная Республика Танзания",
    eng: "United Republic of Tanzania",
  },
  { rus: "Объединенные Арабские Эмираты", eng: "United Arab Emirates" },

  { rus: "Остров Буве", eng: "Bouvet Island" },
  { rus: "Острова Кука", eng: "Cook Islands" },
  { rus: "Остров Мэн", eng: "Isle of Man" },
  {
    rus: "Остров Херд и острова Макдональд",
    eng: "Heard Island and McDonald Islands",
  },
  {
    rus: "Острова Святой Елены, Вознесения и Тристан-да-Кунья",
    eng: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { rus: "Питкэрн группа островов", eng: "Pitcairn Group of Islands" },
  { rus: "Португальская Республика", eng: "Portuguese Republic" },
  { rus: "Республика Албания", eng: "Republic of Albania" },
  { rus: "Республика Ангола", eng: "Republic of Angola" },
  { rus: "Республика Армения", eng: "Republic of Armenia" },
  { rus: "Республика Беларусь", eng: "Republic of Belarus" },
  { rus: "Республика Бенин", eng: "Republic of Benin" },
  { rus: "Республика Болгария", eng: "Republic of Bulgaria" },
  { rus: "Республика Ботсвана", eng: "Republic of Botswana" },
  { rus: "Республика Бурунди", eng: "Republic of Burundi" },
  { rus: "Республика Вануату", eng: "Republic of Vanuatu" },
  { rus: "Республика Гаити", eng: "Republic of Haiti" },
  { rus: "Республика Гамбия", eng: "Republic of the Gambia" },
  { rus: "Республика Гана", eng: "Republic of Ghana" },
  { rus: "Республика Гватемала", eng: "Republic of Guatemala" },
  { rus: "Республика Гвинея", eng: "Republic of Guinea" },
  { rus: "Республика Гвинея -Бисау", eng: "Republic of Guinea-Bissau" },
  { rus: "Республика Гондурас", eng: "Republic of Honduras" },
  { rus: "Республика Джибути", eng: "Republic of Djibouti" },
  { rus: "Республика Замбия", eng: "Republic of Zambia" },
  { rus: "Республика Зимбабве", eng: "Republic of Zimbabwe" },
  { rus: "Республика Индия", eng: "Republic of India" },
  { rus: "Республика Индонезия", eng: "Republic of Indonesia" },
  { rus: "Республика Ирак", eng: "Republic of Iraq" },
  { rus: "Республика Кабо -Верде", eng: "Republic of Cabo Verde" },
  { rus: "Республика Казахстан", eng: "Republic of Kazakhstan" },
  { rus: "Республика Камерун", eng: "Republic of Cameroon" },
  { rus: "Республика Кения", eng: "Republic of Kenya" },
  { rus: "Республика Кипр", eng: "Republic of Cyprus" },
  { rus: "Республика Колумбия", eng: "Republic of Colombia" },
  { rus: "Республика Конго", eng: "Republic of the Congo" },
  { rus: "Республика Корея", eng: "Republic of Korea" },
  { rus: "Республика Косово", eng: "Republic of Kosovo" },
  { rus: "Республика Коста-Рика", eng: "Republic of Costa Rica" },
  { rus: "Республика Кот-д'Ивуаре", eng: "Republic of Côte d'Ivoire" },
  { rus: "Республика Куба", eng: "Republic of Cuba" },
  { rus: "Республика Либерия", eng: "Republic of Liberia" },
  { rus: "Республика Маврикий", eng: "Republic of Mauritius" },
  { rus: "Республика Мадагаскар", eng: "Republic of Madagascar" },
  { rus: "Республика Малави", eng: "Republic of Malawi" },
  { rus: "Республика Мали", eng: "Republic of Mali" },
  { rus: "Республика Мальдивы", eng: "Republic of the Maldives" },
  { rus: "Республика Мальта", eng: "Republic of Malta" },
  {
    rus: "Республика Маршалловы острова",
    eng: "Republic of the Marshall Islands",
  },
  { rus: "Республика Мозамбик", eng: "Republic of Mozambique" },
  { rus: "Республика Намибия", eng: "Republic of Namibia" },
  { rus: "Республика Науру", eng: "Republic of Nauru" },
  { rus: "Республика Нигер", eng: "Republic of Niger" },
  { rus: "Республика Никарагуа", eng: "Republic of Nicaragua" },
  { rus: "Республика Палау", eng: "Republic of Palau" },
  { rus: "Республика Панама", eng: "Republic of Panama" },
  { rus: "Республика Парагвай", eng: "Republic of Paraguay" },
  { rus: "Республика Перу", eng: "Republic of Peru" },
  { rus: "Республика Польша", eng: "Republic of Poland" },
  { rus: "Республика Руанда", eng: "Republic of Rwanda" },
  {
    rus: "Республика Северная Македония",
    eng: "Republic of North Macedonia",
  },
  { rus: "Республика Сейшельские Острова", eng: "Republic of Seychelles" },
  { rus: "Республика Сенегал", eng: "Republic of Senegal" },
  { rus: "Республика Сербия", eng: "Republic of Serbia" },
  { rus: "Республика Сингапур", eng: "Republic of Singapore" },
  { rus: "Республика Словения", eng: "Republic of Slovenia" },
  {
    rus: "Республика Союза Мьянма",
    eng: "Republic of the Union of Myanmar",
  },
  { rus: "Республика Судан", eng: "Republic of the Sudan" },
  { rus: "Республика Суринам", eng: "Republic of Suriname" },
  { rus: "Республика Сьерра-Леоне", eng: "Republic of Sierra Leone" },
  { rus: "Республика Таджикистан", eng: "Republic of Tajikistan" },
  {
    rus: "Республика Тринидад и Тобаго",
    eng: "Republic of Trinidad and Tobago",
  },
  { rus: "Республика Турции", eng: "Republic of Turkey" },
  { rus: "Республика Уганда", eng: "Republic of Uganda" },
  { rus: "Республика Узбекистан", eng: "Republic of Uzbekistan" },
  { rus: "Республика Фиджи", eng: "Republic of Fiji" },
  { rus: "Республика Филиппины", eng: "Republic of the Philippines" },
  { rus: "Республика Хорватия", eng: "Republic of Croatia" },
  { rus: "Республика Чад", eng: "Republic of Chad" },
  { rus: "Республика Чили", eng: "Republic of Chile" },
  { rus: "Республика Эквадор", eng: "Republic of Ecuador" },
  {
    rus: "Республика Экваториальная Гвинея",
    eng: "Republic of Equatorial Guinea",
  },
  { rus: "Республика Эль-Сальвадор", eng: "Republic of El Salvador" },
  { rus: "Республика Южный Судан", eng: "Republic of South Sudan" },
  { rus: "Реюньон", eng: "Réunion Island" },
  { rus: "Российская Федерация", eng: "Russian Federation" },
  { rus: "Румыния", eng: "Romania" },
  {
    rus: "Сахарская Арабская Демократическая Республика",
    eng: "Sahrawi Arab Democratic Republic",
  },
  { rus: "Свальбарда ог Ян-Майен", eng: "Svalbard og Jan Mayen" },
  { rus: "Сен-Мартен", eng: "Saint Martin" },
  { rus: "Сен-Пьер и Микелон", eng: "Saint Pierre and Miquelon" },
  {
    rus: "Сент-Винсент и Гренадины",
    eng: "Saint Vincent and the Grenadines",
  },
  { rus: "Сент-Люсия", eng: "Saint Lucia" },
  { rus: "Синт-Маартен", eng: "Sint Maarten" },
  { rus: "Сирийская Арабская Республика", eng: "Syrian Arab Republic" },
  { rus: "Словацкая Республика", eng: "Slovak Republic" },
  { rus: "Содружество Австралии", eng: "Commonwealth of Australia" },
  {
    rus: "Содружество Багамских Островов",
    eng: "Commonwealth of the Bahamas",
  },
  { rus: "Содружество Доминики", eng: "Commonwealth of Dominica" },
  { rus: "Содружество Пуэрто-Рико", eng: "Commonwealth of Puerto Rico" },
  {
    rus: "Содружество Северных Марианских островов",
    eng: "Commonwealth of the Northern Mariana Islands",
  },
  {
    rus: "Соединенное Королевство Великобритании и Северной Ирландии",
    eng: "United Kingdom of Great Britain and Northern Ireland",
  },
  { rus: "Соединенные Штаты Америки", eng: "United States of America" },
  { rus: "Соломоновы острова", eng: "Solomon Islands" },
  {
    rus: "Социалистическая Республика Вьетнам",
    eng: "Socialist Republic of Vietnam",
  },
  { rus: "Союз Коморских Островов", eng: "Union of the Comoros" },
  {
    rus: "Специальный административный район Макао Китайской Народной Республики Китай",
    eng: "Macao Special Administrative Region of the People's Republic of China",
  },
  { rus: "Страна Кюрасао", eng: "Country of Curaçao" },
  { rus: "Султанат Оман", eng: "Sultanate of Oman" },
  { rus: "Теркс и Кайкос острова", eng: "Turks and Caicos Islands" },
  {
    rus: "Территория Кокосовые (Килинг) острова",
    eng: "Territory of the Cocos (Keeling) Islands",
  },
  {
    rus: "Территория Уоллис и Футуна острова",
    eng: "Territory of the Wallis and Futuna Islands",
  },
  {
    rus: "Территория Французские Южные и Антарктические земли",
    eng: "Territory of the French Southern and Antarctic Lands",
  },
  { rus: "Территория острова Норфолк", eng: "Territory of Norfolk Island" },
  {
    rus: "Территория острова Рождества",
    eng: "Territory of Christmas Island",
  },
  { rus: "Того Республика", eng: "Togolese Republic" },
  { rus: "Токелау", eng: "Tokelau" },
  { rus: "Тувалу", eng: "Tuvalu" },
  { rus: "Тунисской Республики", eng: "Tunisian Republic" },
  { rus: "Туркменистан", eng: "Turkmenistan" },
  { rus: "Украина", eng: "Ukraine" },
  { rus: "Фарерские острова", eng: "Faroe Islands" },
  {
    rus: "Федеративная Демократическая Республика Непал",
    eng: "Federal Democratic Republic of Nepal",
  },
  {
    rus: "Федеративная Демократическая Республика Эфиопия",
    eng: "Federal Democratic Republic of Ethiopia",
  },
  {
    rus: "Федеративная Республика Бразилия",
    eng: "Federative Republic of Brazil",
  },
  {
    rus: "Федеративная Республика Германия",
    eng: "Federal Republic of Germany",
  },
  {
    rus: "Федеративная Республика Нигерия",
    eng: "Federal Republic of Nigeria",
  },
  {
    rus: "Федеративная Республика Сомали",
    eng: "Federal Republic of Somalia",
  },
  {
    rus: "Федеративные Штаты Микронезии",
    eng: "Federated States of Micronesia",
  },
  {
    rus: "Федерация Сент-Кристофер и Н е в и с",
    eng: "Federation of Saint Christopher and Nevis",
  },
  { rus: "Финляндская Республика", eng: "Republic of Finland" },
  { rus: "Фолклендские острова", eng: "Falkland Islands" },
  { rus: "Французская Полинезия", eng: "French Polynesia" },
  { rus: "Французская Республика", eng: "French Republic" },
  {
    rus: "Центрально-Африканская Республика",
    eng: "Central African Republic",
  },
  { rus: "Черногория", eng: "Montenegro" },
  { rus: "Чешская Республика", eng: "Czech Republic" },
  { rus: "Швейцарская Конфедерация", eng: "Swiss Confederation" },
  { rus: "Эстонская Республика", eng: "Republic of Estonia" },
  {
    rus: "Южная Георгия и Южные Сандвичевы острова",
    eng: "South Georgia and the South Sandwich Islands",
  },
  { rus: "Южно-Африканская Республика", eng: "Republic of South Africa" },
  { rus: "Ямайка", eng: "Jamaica" },
  { rus: "Япония", eng: "Japan" },
];
export default countries;
